
nav:
  -
    text: 系统概览
    icon: dashboard
    path: 'index/index'
  -
    text: 通知公告
    icon: envelope
    path: 'posts/index'
  -
    text: 用户管理
    icon: user
    path: 'users/index'
  -
    text: 作品管理
    icon: film
    path: 'creations/index'
  -
    text: 作品评审
    icon: ok
    path: judge/index
  -
    text: 管理员管理
    icon: star
    path: 'admins/index'
  -
    text: 个人信息管理
    icon: edit
    path: 'admins/edit_self'
