# 请按照以下格式来添加节点
# controller1:
#   action1:
#     title: something
#     remark: something in detail
#   action2:
#     title: something
#     remark: something in detail
#
# controller2:
#   action1:
#     title: something
#     remark: something in detail
#   action2:
#     title: something
#     remark: something in detail
admins:
  index:
    title:  查看管理员列表
    remark: 列出管理员，查看管理员的大致信息
  new:
    title:  添加管理员
    remark: 添加一个新的管理员账户
  edit:
    title:  编辑信息
    remark: 编辑管理员的基本信息，或者管理员的权限
  show:
    title:  查看详细信息
    remark: 查看管理员详细信息
  destroy:
    title:  删除管理员
    remark: 删除管理员
  edit_role:
    title:  编辑角色权限
    remark: 修改角色的权限，或者角色的名字
  destroy_role:
    title:  删除角色
    remark: 删除角色
  create_role:
    title:  新建角色
    remark: 新建一个角色
  show_role:
    title:  查看角色权限
    remark: 查看角色的权限

posts:
  index:
    title:  查看公告列表
    remark: 查看所有的通知公告
  new:
    title: 新建通知公告
    remark: 新建一个通知公告
  edit:
    title: 编辑通知公告
    remark: 编辑通知公告
  show:
    title:  查看公告详细
    remark: 查看完整的通知公告
  destroy:
    title:  删除通知公告
    remark: 删除通知公告

users:
  index:
    title:  查看用户列表
    remark: 查看全部用户
  new:
    title: 新建用户
    remark: 新建一个用户
  edit:
    title: 编辑用户
    remark: 编辑用户信息
  show:
    title:  查看用户信息
    remark: 查看用户详细信息
  destroy:
    title:  删除用户
    remark: 删除用户

creations:
  index:
    title:  查看作品列表
    remark: 查看所有的作品

comment:
  index:
    title: 查看评论列表
    remark: 查看所有的评论

judge:
  index:
    title:  查看作品评审
    remark: 查看作品评审的主页

cfg:
  index:
    title:  查看设置项
    remark: 查看全部设置项列表
  update:
    title: 修改系统设置
    remark: 修改系统设置
