admin:
  list:
    title: 查看管理员列表
    remark: 列出管理员，查看管理员的大致信息
  add:
    title: 添加管理员
    remark: 添加一个新的管理员账户
  edit:
    title: 编辑信息
    remark: 编辑管理员的基本信息，或者管理员的权限
  show:
    title: 查看详细信息
    remark: 查看管理员详细信息
  delete:
    title: 删除管理员
    remark: 删除管理员

test_controller:
  exam_action1:
    title: hhhh
    remark: adfsgfg
  exam_action2:
    title: asdasd
    remark: asd432
